export const GET_CHANNELS_SUCCESS = 'GET_CHANNELS_SUCCESS';
export const GET_CHANNELS_FAIL = 'GET_CHANNELS_FAIL';
export const GET_CHANNELS = 'GET_CHANNELS';

export const GET_CHANNEL_MESSAGES_SUCCESS = 'GET_CHANNEL_MESSAGES_SUCCESS';
export const GET_CHANNEL_MESSAGES_FAIL = 'GET_CHANNEL_MESSAGES_FAIL';
export const GET_CHANNEL_MESSAGES = 'GET_CHANNEL_MESSAGES';

export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_FAIL = 'CREATE_CHANNEL_FAIL';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';

export const UPDATE_CHANNEL_DETAILS = 'UPDATE_CHANNEL_DETAILS';
export const UPDATE_CHANNEL_DETAILS_SUCCESS = 'UPDATE_CHANNEL_DETAILS_SUCCESS';
export const UPDATE_CHANNEL_DETAILS_FAILURE = 'UPDATE_CHANNEL_DETAILS_FAILURE';

export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';
export const DELETE_CHANNEL_FAILURE = 'DELETE_CHANNEL_FAILURE';

export const GET_CHANNEL_GROUP_REQUEST = 'GET_CHANNEL_GROUP_REQUEST';
export const GET_CHANNEL_GROUP_SUCCESS = 'GET_CHANNEL_GROUP_SUCCESS';
export const GET_CHANNEL_GROUP_FAILURE = 'GET_CHANNEL_GROUP_FAILURE';

export const GET_GROUP_CHATS_REQUEST = 'GET_GROUP_CHATS_REQUEST';
export const GET_GROUP_CHATS_SUCCESS = 'GET_GROUP_CHATS_SUCCESS';
export const GET_GROUP_CHATS_FAILURE = 'GET_GROUP_CHATS_FAILURE';
export const CLEAR_GROUP_CHAT_MESSAGES = 'CLEAR_GROUP_CHAT_MESSAGES';

// ban player
export const BAN_PLAYER_SUCCESS = 'BAN_PLAYER_SUCCESS';
export const BAN_PLAYER_FAILURE = 'BAN_PLAYER_FAILURE';
export const BAN_PLAYER = 'BAN_PLAYER';
