/** Get Admins */
export const GET_ALL_GROUP_START = 'GET_ALL_GROUP_START';
export const GET_ALL_GROUP_SUCCESS = 'GET_ALL_GROUP_SUCCESS';
export const GET_ALL_GROUP_FAIL = 'GET_ALL_GROUP_FAIL';

export const UPDATE_SUPER_ADMIN_STATUS_START =
	'UPDATE_SUPER_ADMIN_STATUS_START';
export const UPDATE_SUPER_ADMIN_STATUS_SUCCESS =
	'UPDATE_SUPER_ADMIN_STATUS_SUCCESS';
export const UPDATE_SUPER_ADMIN_STATUS_FAIL = 'UPDATE_SUPER_ADMIN_STATUS_FAIL';
