export const GET_AGGREGATORS_START = 'GET_AGGREGATORS_START';
export const GET_AGGREGATORS_FAILURE = 'GET_AGGREGATORS_FAILURE';
export const GET_AGGREGATORS_SUCCESS = 'GET_AGGREGATORS_SUCCESS';

export const CREATE_AGGREGATORS_START = 'CREATE_AGGREGATORS_START';
export const CREATE_AGGREGATORS_FAIL = 'CREATE_AGGREGATORS_FAIL';
export const CREATE_AGGREGATORS_SUCCESS = 'CREATE_AGGREGATORS_SUCCESS';

export const UPDATE_AGGREGATORS_STATUS_START =
	'UPDATE_AGGREGATORS_STATUS_START';
export const UPDATE_AGGREGATORS_STATUS_FAIL = 'UPDATE_AGGREGATORS_STATUS_FAIL';
export const UPDATE_AGGREGATORS_STATUS_SUCCESS =
	'UPDATE_AGGREGATORS_STATUS_SUCCESS';
