export const FETCH_CHATRULE_START = 'FETCH_CHATRULE_START';
export const FETCH_CHATRULE_FAIL = 'FETCH_CHATRULE_FAIL';
export const FETCH_CHATRULE_SUCCESS = 'FETCH_CHATRULE_SUCCESS';
export const DELETE_CHATRULE = 'DELETE_CHATRULE';

//  CREATE OFFENSIVE WORDS
export const CREATE_CHATRULE_START = 'CREATE_CHATRULE_START';
export const CREATE_CHATRULE_SUCCESS = 'CREATE_CHATRULE_SUCCESS';
export const CREATE_CHATRULE_FAIL = 'CREATE_CHATRULE_FAIL';

// EDIT OFFENSIVE WORDS
export const EDIT_CHATRULE_START = 'EDIT_CHATRULE_START';
export const EDIT_CHATRULE_SUCCESS = 'EDIT_CHATRULE_SUCCESS';
export const EDIT_CHATRULE_FAIL = 'EDIT_CHATRULE_FAIL';
