// Get get-currency-limit view
export const GET_CURRENCY_LIMIT_START = 'GET_CURRENCY_LIMIT_START';
export const GET_CURRENCY_LIMIT_SUCCESS = 'GET_CURRENCY_LIMIT_SUCCESS';
export const GET_CURRENCY_LIMIT_FAIL = 'GET_CURRENCY_LIMIT_FAIL';
// updateWithdrawlimit
export const UPDATE_WITHDRAW_LIMIT_START = 'UPDATE_WITHDRAW_LIMIT_START';
export const UPDATE_WITHDRAW_LIMIT_SUCCESS = 'UPDATE_WITHDRAW_LIMIT_SUCCESS';
export const UPDATE_WITHDRAW_LIMIT_FAIL = 'UPDATE_WITHDRAW_LIMIT_FAIL';
// updateDepositlimit
export const UPDATE_DEPOSIT_LIMIT_START = 'UPDATE_DEPOSIT_LIMIT_START';
export const UPDATE_DEPOSIT_LIMIT_SUCCESS = 'UPDATE_DEPOSIT_LIMIT_SUCCESS';
export const UPDATE_DEPOSIT_LIMIT_FAIL = 'UPDATE_DEPOSIT_LIMIT_FAIL';
// getAffiliateCommisionPerc
export const GET_AFFILIATE_COMNISION_PERC_START =
	'GET_AFFILIATE_COMNISION_PERC_START';
export const GET_AFFILIATE_COMNISION_PERC_SUCCESS =
	'GET_AFFILIATE_COMNISION_PERC_SUCCESS';
export const GET_AFFILIATE_COMNISION_PERC_FAIL =
	'GET_AFFILIATE_COMNISION_PERC_FAIL';
// getAffiliateCommisionPerc
export const UPDATE_AFFILIATE_COMNISION_PERC_START =
	'UPDATE_AFFILIATE_COMNISION_PERC_START';
export const UPDATE_AFFILIATE_COMNISION_PERC_SUCCESS =
	'UPDATE_AFFILIATE_COMNISION_PERC_SUCCESS';
export const UPDATE_AFFILIATE_COMNISION_PERC_FAIL =
	'UPDATE_AFFILIATE_COMNISION_PERC_FAIL';
// getReferralCommisionAmount
export const GET_REFERRAL_COMNISION_AMOUNT_START =
	'GET_REFERRAL_COMNISION_AMOUNT_START';
export const GET_REFERRAL_COMNISION_AMOUNT_SUCCESS =
	'GET_REFERRAL_COMNISION_AMOUNT_SUCCESS';
export const GET_REFERRAL_COMNISION_AMOUNT_FAIL =
	'GET_REFERRAL_COMNISION_AMOUNT_FAIL';
// updateReferralCommisionAmount
export const UPDATE_REFERRAL_COMNISION_AMOUNT_START =
	'UPDATE_REFERRAL_COMNISION_AMOUNT_START';
export const UPDATE_REFERRAL_COMNISION_AMOUNT_SUCCESS =
	'UPDATE_REFERRAL_COMNISION_AMOUNT_SUCCESS';
export const UPDATE_REFERRAL_COMNISION_AMOUNT_FAIL =
	'UPDATE_REFERRAL_COMNISION_AMOUNT_FAIL';
