export const FETCH_OFFENSIVE_WORDS_START = 'FETCH_OFFENSIVE_WORDS_START';
export const FETCH_OFFENSIVE_WORDS_FAIL = 'FETCH_OFFENSIVE_WORDS_FAIL';
export const FETCH_OFFENSIVE_WORDS_SUCCESS = 'FETCH_OFFENSIVE_WORDS_SUCCESS';
export const DELETE_OFFENSIVE_WORDS = 'DELETE_OFFENSIVE_WORDS';

//  CREATE OFFENSIVE WORDS
export const CREATE_OFFENSIVE_WORDS_START = 'CREATE_OFFENSIVE_WORDS_START';
export const CREATE_OFFENSIVE_WORDS_SUCCESS = 'CREATE_OFFENSIVE_WORDS_SUCCESS';
export const CREATE_OFFENSIVE_WORDS_FAIL = 'CREATE_OFFENSIVE_WORDS_FAIL';

// EDIT OFFENSIVE WORDS
export const EDIT_OFFENSIVE_WORDS_START = 'EDIT_OFFENSIVE_WORDS_START';
export const EDIT_OFFENSIVE_WORDS_SUCCESS = 'EDIT_OFFENSIVE_WORDS_SUCCESS';
export const EDIT_OFFENSIVE_WORDS_FAIL = 'EDIT_OFFENSIVE_WORDS_FAIL';
