/** Get wagering template */
export const GET_WAGERING_TEMPLATE_DETAIL_SUCCESS =
	'GET_WAGERING_TEMPLATE_DETAIL_SUCCESS';
export const GET_WAGERING_TEMPLATE_DETAIL_FAIL =
	'GET_WAGERING_TEMPLATE_DETAIL_FAIL';
export const GET_WAGERING_TEMPLATE_DETAIL = 'GET_WAGERING_TEMPLATE_DETAIL';

/** Get all wagering template */
export const GET_WAGERING_TEMPLATE_DETAILS_SUCCESS =
	'GET_WAGERING_TEMPLATE_DETAILS_SUCCESS';
export const GET_ALL_WAGERING_TEMPLATE_DETAILS_FAIL =
	'GET_WAGERING_TEMPLATE_DETAILS_FAIL';
export const GET_WAGERING_TEMPLATE_DETAILS = 'GET_WAGERING_TEMPLATE_DETAILS';

/** Create wagering template */
export const CREATE_WAGERING_TEMPLATE_DETAILS_SUCCESS =
	'CREATE_WAGERING_TEMPLATE_DETAILS_SUCCESS';
export const CREATE_WAGERING_TEMPLATE_DETAILS_FAIL =
	'CREATE_WAGERING_TEMPLATE_DETAILS_FAIL';
export const CREATE_WAGERING_TEMPLATE_DETAILS =
	'CREATE_WAGERING_TEMPLATE_DETAILS';

/** Edit wagering template */
export const EDIT_WAGERING_TEMPLATE_DETAILS_SUCCESS =
	'EDIT_WAGERING_TEMPLATE_DETAILS_SUCCESS';
export const EDIT_WAGERING_TEMPLATE_DETAILS_FAIL =
	'EDIT_WAGERING_TEMPLATE_DETAILS_FAIL';
export const EDIT_WAGERING_TEMPLATE_DETAILS = 'EDIT_WAGERING_TEMPLATE_DETAILS';

/** Get all SA wagering template */
export const GET_ALL_SA_WAGERING_TEMPLATES_SUCCESS =
	'GET_ALL_SA_WAGERING_TEMPLATES_SUCCESS';
export const GET_ALL_SA_WAGERING_TEMPLATES_FAIL =
	'GET_ALL_SA_WAGERING_TEMPLATES_FAIL';
export const GET_ALL_SA_WAGERING_TEMPLATES = 'GET_ALL_SA_WAGERING_TEMPLATES';
