export const GET_ALL_VIP_TIERS = 'GET_ALL_VIP_TIERS';
export const GET_ALL_VIP_TIERS_SUCCESS = 'GET_ALL_VIP_TIERS_SUCCESS';
export const GET_ALL_VIP_TIERS_FAIL = 'GET_ALL_VIP_TIERS_FAIL';

export const GET_VIP_TIER = 'GET_VIP_TIER';
export const GET_VIP_TIER_SUCCESS = 'GET_VIP_TIER_SUCCESS';
export const GET_VIP_TIER_FAIL = 'GET_VIP_TIER_FAIL';

export const CREATE_VIP_TIER = 'CREATE_VIP_TIER';
export const CREATE_VIP_TIER_SUCCESS = 'CREATE_VIP_TIER_SUCCESS';
export const CREATE_VIP_TIER_FAIL = 'CREATE_VIP_TIER_FAIL';

export const UPDATE_VIP_TIER = 'UPDATE_VIP_TIER';
export const UPDATE_VIP_TIER_SUCCESS = 'UPDATE_VIP_TIER_SUCCESS';
export const UPDATE_VIP_TIER_FAIL = 'UPDATE_VIP_TIER_FAIL';
