import { isEmpty } from 'lodash';
import { modules } from './permissions';
// import { mode } from 'crypto-js';

const sideBarElements = [
	{
		isSeparator: true,
		title: 'Menu',
		separatorModule: [
			modules.KYC,
			modules.Administrator,
			modules.AppConfiguration,
		],
	},
	{
		id: 1,
		link: '/dashboard',
		label: 'Dashboard',
		searchString: 'default dashboard home',
		iconName: 'bx bx-home-circle',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.Reports,
	},
	{
		id: 2,
		link: '/profile',
		label: 'Profile',
		searchString: 'profile account my account',
		iconName: 'bx bxs-user-circle',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
	},
	{
		id: 3,
		link: '/#',
		label: 'Administrator',
		searchString: 'administrator',
		iconName: 'bx bx-user-plus',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupModules: [modules.Administrator],
		subMenu: [
			// {
			// 	id: 4,
			// 	link: '/roles',
			// 	label: 'Roles',
			// 	searchString: 'roles listing',
			// 	iconName: 'bx bx-user-plus',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.Administrator,
			// },
			{
				id: 5,
				link: '/staff',
				label: 'Staff',
				searchString: 'staff admin superadmin listing',
				iconName: 'bx bx-user-plus',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Administrator,
			},
		],
	},
	{
		id: 60,
		link: '/#',
		label: 'AMOE',
		searchString: 'AMOE',
		iconName: 'mdi mdi-cash',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupModules: [modules.AMOE],
		subMenu: [
			{
				id: 50,
				link: '/faucet-settings',
				label: 'Faucet Settings',
				searchString: 'faucet settings',
				iconName: 'mdi mdi-cash',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
		],
	},
	{
		id: 7,
		link: '/users',
		label: 'Players',
		searchString: 'all users',
		iconName: 'bx bx-group',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.Players,
	},
	{
		id: 27,
		link: '/#',
		label: 'Player Engagement',
		searchString: 'engagement',
		iconName: 'bx bxs-crown',
		linkClass: 'has-arrow',
		groupModules: [modules.PlayerEngagement],
		subMenu: [
			{
				id: 28,
				link: '/spin-wheel',
				label: 'Spin Wheel',
				searchString: 'default dashboard home',
				// iconName: 'bx bx-color',
				iconName: 'bx bxs-buoy',

				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.PlayerEngagement,
			},
			{
				id: 29,
				link: '/vip-tier',
				label: 'Vip Tier',
				searchString: 'vip tier',
				iconName: 'bx bxs-crown',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.PlayerEngagement,
			},
			// {
			// 	id: 50,
			// 	link: '/faucet-settings',
			// 	label: 'Faucet Settings',
			// 	searchString: 'faucet settings',
			// 	iconName: 'bx bxs-dollar-circle',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// },
			{
				id: 51,
				link: '/notice',
				label: 'Notice',
				searchString: 'notice',
				iconName: 'bi bi-bell',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.PlayerEngagement,
			},
		],
	},

	// {
	// 	id: 40,
	// 	link: '/#',
	// 	label: 'Affiliates',
	// 	searchString: 'all affiliates',
	// 	iconName: 'bx bxs-shopping-bag',
	// 	linkClass: 'has-arrow',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	groupModules: [modules.Affiliates],
	// 	subMenu: [
	// 		{
	// 			id: 46,
	// 			link: '/affiliate-requests',
	// 			label: 'Affiliate Requests',
	// 			searchString: 'affiliate request',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.Affiliates,
	// 		},
	// 		{
	// 			id: 47,
	// 			link: '/affiliate-details',
	// 			label: 'Affiliate Details',
	// 			searchString: 'affiliate details',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.Affiliates,
	// 		},
	// 		{
	// 			id: 48,
	// 			link: '/affiliate-settings',
	// 			label: 'Affiliate Settings',
	// 			searchString: 'affiliate settings',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.Affiliates,
	// 		},
	// 	],
	// },
	// {
	// 	id: 41,
	// 	link: '/demographics',
	// 	label: 'Demographics',
	// 	searchString: 'all demograph',
	// 	iconName: 'bx bx-street-view',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.DemographReport,
	// },

	// {
	// 	id: 49,
	// 	link: '/kyc-settings',
	// 	label: 'KYC Settings',
	// 	searchString: 'kyc settings',
	// 	iconName: 'bx bx-list-check',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.KYC,
	// },

	// {
	// 	id: 5,
	// 	link: '/kyc-labels',
	// 	label: 'KYC Labels',
	// 	searchString: 'kyc labels',
	// 	iconName: 'bx bx-list-check',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.KYC,
	// },
	// {
	// 	id: 8,
	// 	link: '/global-setting',
	// 	label: 'Site Configuration',
	// 	searchString: 'site configuration',
	// 	iconName: 'bx bx-cog',
	// 	linkClass: 'has-arrow',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	groupModules: [modules.AppConfiguration],
	// 	subMenu: [
	// 		// {
	// 		// 	id: 9,
	// 		// 	link: '/currencies',
	// 		// 	label: 'Currencies',
	// 		// 	searchString: 'currencies',
	// 		// 	iconName: '',
	// 		// 	linkClass: '',
	// 		// 	anchorClass: '',
	// 		// 	spanClass: '',
	// 		// 	liTagClass: '',
	// 		// 	ulTagClass: '',
	// 		// 	module: modules.AppConfiguration,
	// 		// },
	// 		// {
	// 		// 	id: 42,
	// 		// 	link: '/countries',
	// 		// 	label: 'Countries',
	// 		// 	searchString: 'countries',
	// 		// 	iconName: '',
	// 		// 	linkClass: '',
	// 		// 	anchorClass: '',
	// 		// 	spanClass: '',
	// 		// 	liTagClass: '',
	// 		// 	ulTagClass: '',
	// 		// 	module: modules.RestrictedCountry,
	// 		// },
	// 		// {
	// 		// 	id: 8,
	// 		// 	link: '/languages',
	// 		// 	label: 'Languages',
	// 		// 	searchString: 'languages',
	// 		// 	iconName: '',
	// 		// 	linkClass: '',
	// 		// 	anchorClass: '',
	// 		// 	spanClass: '',
	// 		// 	liTagClass: '',
	// 		// 	ulTagClass: '',
	// 		// 	module: modules.MultiLanguage,
	// 		// },
	// 		// {
	// 		// 	id: 9,
	// 		// 	link: '/languages-management',
	// 		// 	label: 'Languages Management',
	// 		// 	searchString: 'languages management',
	// 		// 	iconName: '',
	// 		// 	linkClass: '',
	// 		// 	anchorClass: '',
	// 		// 	spanClass: '',
	// 		// 	liTagClass: '',
	// 		// 	ulTagClass: '',
	// 		// 	module: modules.MultiLanguage,
	// 		// },
	// 		// {
	// 		// 	id: 10,
	// 		// 	link: '/form-fields',
	// 		// 	label: 'Registration Fields',
	// 		// 	searchString: 'registration fields',
	// 		// 	iconName: '',
	// 		// 	linkClass: '',
	// 		// 	anchorClass: '',
	// 		// 	spanClass: '',
	// 		// 	liTagClass: '',
	// 		// 	ulTagClass: '',
	// 		// 	module: modules.RegistrationField,
	// 		// },
	// 		{
	// 			id: 10,
	// 			link: '/global-setting',
	// 			label: 'Global Settings',
	// 			searchString: '  ',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.AppConfiguration,
	// 		},
	// 	],
	// },
	{
		id: 10,
		link: '/global-setting',
		label: 'Site Configuration',
		searchString: '  ',
		iconName: 'bx bx-cog',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.AppConfiguration,
	},
	{
		id: 11,
		link: '/#',
		label: 'Content Management',
		searchString: 'content management',
		iconName: 'bx bx-customize',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupModules: [modules.ContentManagement],
		subMenu: [
			{
				id: 12,
				link: '/cms',
				label: 'CMS',
				searchString: 'cms',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.ContentManagement,
			},
			{
				id: 13,
				link: '/email-templates',
				label: 'CRM',
				searchString: 'email crm',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				// module: modules.EmailTemplate,
			},
			// {
			// 	id: 44,
			// 	link: '/email-players',
			// 	label: 'E-mail Players',
			// 	searchString: 'email crm',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	// module: modules.EmailTemplate,
			// },
			// {
			// 	id: 13,
			// 	link: '/image-gallery',
			// 	label: 'Image Gallery',
			// 	searchString: 'image gallery',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.ContentManagement,
			// },
			{
				id: 14,
				link: '/promotions',
				label: 'Promotions',
				searchString: 'promotion management sponsorship management',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.ContentManagement,
			},
			{
				id: 15,
				link: '/banner-management',
				label: 'Banner Management',
				searchString: 'banner management home banner',
				iconName: 'mdi mdi-file-presentation-box',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.ContentManagement,
			},
			{
				id: 44,
				link: '/social-links',
				label: 'Social',
				searchString: 'banner management home banner',
				iconName: 'mdi mdi-file-presentation-box',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.ContentManagement,
			},
		],
	},

	{
		isSeparator: true,
		title: 'Casino 	service',
		separatorModule: [modules.CasinoManagement],
	},
	{
		id: 16,
		link: '/#',
		label: 'Casino Management',
		searchString: 'casino management slot',
		iconName: 'bx bx-list-ul',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupModules: [modules.CasinoManagement],
		subMenu: [
			{
				id: 17,
				link: '/casino-aggregators',
				label: 'Aggregators',
				searchString: 'casino aggregators',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			{
				id: 18,
				link: '/casino-providers',
				label: 'Providers',
				searchString: 'casino providers',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			{
				id: 19,
				link: '/categories',
				label: 'Categories',
				searchString: 'casino categories',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
			// {
			// 	id: 19,
			// 	link: '/sub-categories',
			// 	label: 'Sub Categories',
			// 	searchString: 'casino sub categories',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.CasinoManagement,
			// },
			{
				id: 20,
				link: '/casino-games',
				label: 'Games',
				searchString: 'casino games',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.CasinoManagement,
			},
		],
	},

	{
		isSeparator: true,
		title: 'Reward administration',
		separatorModule: [
			// modules.LoyaltyManagement,
			// modules.WageringTemplate,
			modules.Bonus,
		],
	},
	{
		id: 21,
		link: '/bonus',
		label: 'Bonus',
		searchString: 'bonus',
		iconName: 'bx bxs-dollar-circle',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.Bonus,
	},
	// {
	//   id: 22,
	//   link: '/#',
	//   label: 'Bonus Management',
	//   searchString: 'bonus management',
	//   iconName: 'bx bx-money',
	//   linkClass: 'has-arrow',
	//   anchorClass: '',
	//   spanClass: '',
	//   liTagClass: '',
	//   ulTagClass: '',
	//   subMenu: [
	// {
	// 	id: 23,
	// 	link: '/loyalty-management',
	// 	label: 'Loyalty Management',
	// 	searchString: 'loyalty management',
	// 	iconName: '',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.LoyaltyManagement,
	// },
	// {
	// 	id: 24,
	// 	link: '/wagering-template',
	// 	label: 'Wagering Template',
	// 	searchString: 'wagering template',
	// 	iconName: '',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.WageringTemplate,
	// },
	//   {
	//     id: 25,
	//     link: '/bonus',
	//     label: 'Bonus',
	//     searchString: 'bonus',
	//     iconName: '',
	//     linkClass: '',
	//     anchorClass: '',
	//     spanClass: '',
	//     liTagClass: '',
	//     ulTagClass: '',
	//     module: modules.Bonus,
	//   },
	// ],
	//   },

	{
		isSeparator: true,
		title: 'Statements',
		moduole: modules.Reports,
	},
	{
		id: 22,
		link: '/#',
		label: 'Reports',
		searchString: 'reports',
		iconName: 'bx bxs-report',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		groupModules: [modules.Reports],
		subMenu: [
			{
				id: 23,
				link: '/transaction-banking',
				label: 'Transactions Banking',
				searchString: 'transaction banking',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Reports,
			},
			{
				id: 24,
				link: '/casino-transactions',
				label: 'Casino Transactions',
				searchString: 'casino transactions',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				module: modules.Reports,
			},
			{
				id: 25,
				link: '/redeem-request',
				label: 'Redeem Request',
				searchString: 'redeem-request',
				iconName: 'mdi mdi-cash',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				id: 30,
				link: '/player-report',
				label: 'Player Report',
				searchString: 'player-report',
				iconName: 'mdi mdi-cash',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			{
				id: 31,
				link: '/game-report',
				label: 'Game Report',
				searchString: 'game-report',
				iconName: 'mdi mdi-cash',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
			},
			// {
			// 	id: 29,
			// 	link: '/sports-transactions',
			// 	label: 'Sports Transactions',
			// 	searchString: 'sports transactions',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.Reports,
			// },
			// {
			// 	id: 30,
			// 	link: '/withdraw-request',
			// 	label: 'Withdraw Request',
			// 	searchString: 'withdraw requests',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.Reports,
			// },
			// {
			// 	id: 31,
			// 	link: '/review-management',
			// 	label: 'Review Management',
			// 	searchString: 'review management',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	module: modules.Reviews,
			// },
		],
	},
	{
		id: 26,
		link: '/packages',
		label: 'Packages',
		searchString: 'packages',
		iconName: 'bx bxs-truck',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		module: modules.Packages,
	},
	{
		id: 32,
		link: '/#',
		label: 'Support',
		searchString: 'support',
		iconName: 'bx bxs-help-circle',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		// groupModules: [modules.TicketManagement],
		subMenu: [
			{
				id: 33,
				link: '/ticket-management',
				label: 'Ticket Management',
				searchString: 'ticket management',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				// module: modules.TicketManagement,
			},
		],
	},

	{
		id: 38,
		link: '/#',
		label: 'Chat Management',
		searchString: 'chat management',
		iconName: 'bx bx-group',
		linkClass: 'has-arrow',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		// groupedModules: [modules.paymentManagement],
		subMenu: [
			// {
			// 	id: 40,
			// 	link: '/chat/channels',
			// 	label: 'Channels',
			// 	searchString: 'channels',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	// module: modules.paymentManagement,
			// },
			{
				id: 41,
				link: '/chat/offensive-words',
				label: 'Offensive Words',
				searchString: 'channels',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				// module: modules.paymentManagement,
			},
			// {
			// 	id: 116,
			// 	link: '/chat/chat-rain',
			// 	label: 'Chat Rain',
			// 	searchString: 'chat rain',
			// 	iconName: '',
			// 	linkClass: '',
			// 	anchorClass: '',
			// 	spanClass: '',
			// 	liTagClass: '',
			// 	ulTagClass: '',
			// 	// module: modules.paymentManagement,
			// },
			{
				id: 42,
				link: '/chat/chat-rule',
				label: 'Chat Rule',
				searchString: 'chat rule',
				iconName: '',
				linkClass: '',
				anchorClass: '',
				spanClass: '',
				liTagClass: '',
				ulTagClass: '',
				// module: modules.paymentManagement,
			},
		],
	},
	{
		id: 43,
		link: '/bonus-drop',
		label: 'Bonus Drop',
		searchString: 'bonus drop',
		iconName: 'bx bxs-droplet',
		linkClass: '',
		anchorClass: '',
		spanClass: '',
		liTagClass: '',
		ulTagClass: '',
		// module: modules.Packages,
	},
	// {
	// 	isSeparator: true,
	// 	title: 'Sports Management',
	// separatorModule: [
	//   modules.BetSettings,
	//   modules.SportbookManagement,
	// ]
	// },
	// {
	// 	id: 32,
	// 	link: '/bet-settings',
	// 	label: 'Bet Settings',
	// 	searchString: 'bet settings',
	// 	iconName: 'bx bx-bar-chart-square',
	// 	linkClass: '',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	module: modules.BetSettings,
	// },
	// {
	// 	id: 33,
	// 	link: '/#',
	// 	label: 'Sports Book',
	// 	searchString: 'sportsbook sports book',
	// 	iconName: 'bx bx-football',
	// 	linkClass: 'has-arrow',
	// 	anchorClass: '',
	// 	spanClass: '',
	// 	liTagClass: '',
	// 	ulTagClass: '',
	// 	subMenu: [
	// 		{
	// 			id: 34,
	// 			link: '/sports',
	// 			label: 'Sports',
	// 			searchString: 'all sports',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.SportbookManagement,
	// 		},
	// 		{
	// 			id: 35,
	// 			link: '/sports/countries',
	// 			label: 'Countries',
	// 			searchString: 'sports countries',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.SportbookManagement,
	// 		},
	// 		{
	// 			id: 36,
	// 			link: '/sports/leagues',
	// 			label: 'Leagues',
	// 			searchString: 'sports leagues',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.SportbookManagement,
	// 		},
	// 		{
	// 			id: 38,
	// 			link: '/matches',
	// 			label: 'Matches',
	// 			searchString: 'sports matches',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.SportbookManagement,
	// 		},
	// 		{
	// 			id: 39,
	// 			link: '/markets',
	// 			label: 'Markets',
	// 			searchString: 'sport match markets',
	// 			iconName: '',
	// 			linkClass: '',
	// 			anchorClass: '',
	// 			spanClass: '',
	// 			liTagClass: '',
	// 			ulTagClass: '',
	// 			module: modules.SportbookManagement,
	// 		},
	// 	],
	// },
];

// For maintaining single source of truth
const getMegaMenuElement = () => {
	try {
		let id = 1;
		const megaMenu = [];
		let megaEle = {};
		let subMenu = [];

		for (let i = 0; i < sideBarElements?.length; i += 1) {
			const tab = sideBarElements[i];
			if (tab.isSeparator) {
				if (!isEmpty(subMenu)) {
					megaEle.subMenu = subMenu;
					megaMenu.push(megaEle);
					subMenu = [];
				}
				megaEle = {
					id,
					link: '#!',
					label: tab.title,
					separatorModule: tab?.separatorModule,
				};
				id += 1;
			} else {
				subMenu.push(tab);
				if (!isEmpty(tab.subMenu)) {
					subMenu.push(...tab.subMenu);
				}
			}
		}
		megaEle.subMenu = subMenu;
		megaMenu.push(megaEle);

		const filterMenu = [];

		megaMenu.forEach((menu) => {
			filterMenu.push({
				...menu,
				subMenu: menu.subMenu.filter((ele) => ele.link !== '/#'),
			});
		});

		return filterMenu;
	} catch (er) {
		// console.log(er);
		return [];
	}
};

export { sideBarElements, getMegaMenuElement };
