const gameContant = {
	game: [
		{
			identifier: 'softswiss:Gemhalla',
			id: 10376,
			name: 'Gemhalla',
			roundCount: '1,363',
			totalBet: '583.65',
			totalWin: '529.35',
			GGR: '54.3',
			playerCount: '2',
			payout: '90.7 %',
		},
		{
			identifier: 'relax:Millionaire',
			id: 8492,
			name: 'Millionaire',
			roundCount: '411',
			totalBet: '227.6',
			totalWin: '191.74',
			GGR: '35.86',
			playerCount: '1',
			payout: '84.24 %',
		},
		{
			identifier: 'pragmaticexternal:WolfGold',
			id: 4807,
			name: 'Wolf Gold',
			roundCount: '358',
			totalBet: '273.5',
			totalWin: '245.9',
			GGR: '27.6',
			playerCount: '1',
			payout: '89.91 %',
		},
		{
			identifier: 'spinomenal:BookofDemiGodsIIReloaded',
			id: 5131,
			name: 'Book of Demi Gods II - Reloaded',
			roundCount: '396',
			totalBet: '249.55',
			totalWin: '131.85',
			GGR: '117.7',
			playerCount: '4',
			payout: '52.84 %',
		},
		{
			identifier: 'pragmaticexternal:TheDogHouseMegaways1',
			id: 4758,
			name: 'The Dog House Megaways',
			roundCount: '327',
			totalBet: '154.6',
			totalWin: '144.09',
			GGR: '10.51',
			playerCount: '2',
			payout: '93.2 %',
		},
		{
			identifier: 'kagaming:ButterflyLovers',
			id: 3026,
			name: 'Butterfly Lovers',
			roundCount: '297',
			totalBet: '142.5',
			totalWin: '128.45',
			GGR: '14.05',
			playerCount: '1',
			payout: '90.14 %',
		},
		{
			identifier: 'evoplay:LuckyPorkerBonusBuy',
			id: 10972,
			name: 'Lucky Porker Bonus Buy',
			roundCount: '233',
			totalBet: '105.5',
			totalWin: '80.54',
			GGR: '24.96',
			playerCount: '1',
			payout: '76.34 %',
		},
		{
			identifier: 'pragmaticexternal:MustangTrail',
			id: 11025,
			name: 'Mustang Trail',
			roundCount: '223',
			totalBet: '334.8',
			totalWin: '473.75',
			GGR: '-138.95',
			playerCount: '1',
			payout: '141.5 %',
		},
		{
			identifier: 'truelab:BookofTruth94',
			id: 3593,
			name: 'Book of Truth',
			roundCount: '137',
			totalBet: '17.73',
			totalWin: '15.05',
			GGR: '2.68',
			playerCount: '1',
			payout: '84.88 %',
		},
		{
			identifier: 'relax:LeBandit92',
			id: 11051,
			name: 'Le Bandit',
			roundCount: '122',
			totalBet: '48.8',
			totalWin: '19.2',
			GGR: '29.6',
			playerCount: '1',
			payout: '39.34 %',
		},
		{
			identifier: 'yggdrasil:FastFruitsDoubleMax',
			id: 10388,
			name: 'Fast Fruits DoubleMax',
			roundCount: '90',
			totalBet: '21.8',
			totalWin: '19.42',
			GGR: '2.38',
			playerCount: '1',
			payout: '89.08 %',
		},
		{
			identifier: 'pragmaticexternal:FatPanda',
			id: 10139,
			name: 'Fat Panda',
			roundCount: '99',
			totalBet: '135',
			totalWin: '55.1',
			GGR: '79.9',
			playerCount: '1',
			payout: '40.81 %',
		},
		{
			identifier: 'pragmaticexternal:BigBassSplash',
			id: 4368,
			name: 'Big Bass Splash',
			roundCount: '91',
			totalBet: '9.1',
			totalWin: '5.95',
			GGR: '3.15',
			playerCount: '1',
			payout: '65.38 %',
		},
		{
			identifier: 'pragmaticexternal:ZeusvsHadesGodsofWar',
			id: 4923,
			name: 'Zeus vs Hades - Gods of War',
			roundCount: '89',
			totalBet: '10.4',
			totalWin: '1.2',
			GGR: '9.2',
			playerCount: '1',
			payout: '11.54 %',
		},
		{
			identifier: 'technology:MagicCrown',
			id: 10511,
			name: 'Magic Crown',
			roundCount: '81',
			totalBet: '8.1',
			totalWin: '6',
			GGR: '2.1',
			playerCount: '1',
			payout: '74.07 %',
		},
		{
			identifier: 'pragmaticexternal:GatesOfOlympus1',
			id: 4531,
			name: 'Gates of Olympus',
			roundCount: '73',
			totalBet: '489.4',
			totalWin: '536.7',
			GGR: '-47.3',
			playerCount: '3',
			payout: '109.66 %',
		},
		{
			identifier: 'softswiss:SavageBuffaloSpirit',
			id: 7303,
			name: 'Savage Buffalo Spirit',
			roundCount: '70',
			totalBet: '70',
			totalWin: '35.2',
			GGR: '34.8',
			playerCount: '1',
			payout: '50.29 %',
		},
		{
			identifier: 'evoplay:WildBullets',
			id: 4092,
			name: 'Wild Bullets',
			roundCount: '64',
			totalBet: '19.2',
			totalWin: '5.19',
			GGR: '14.01',
			playerCount: '1',
			payout: '27.03 %',
		},
		{
			identifier: 'tomhorn:FruitsGoPop',
			id: 4984,
			name: 'Fruits Go Pop!',
			roundCount: '76',
			totalBet: '14.6',
			totalWin: '2.7',
			GGR: '11.9',
			playerCount: '1',
			payout: '18.49 %',
		},
		{
			identifier: 'belatra:LegacyofDoom',
			id: 2036,
			name: 'Legacy of Doom',
			roundCount: '64',
			totalBet: '12.75',
			totalWin: '4.1',
			GGR: '8.65',
			playerCount: '1',
			payout: '32.16 %',
		},
		{
			identifier: 'pragmaticexternal:ForgeofOlympus',
			id: 10872,
			name: 'Forge of Olympus',
			roundCount: '58',
			totalBet: '382.8',
			totalWin: '342.04',
			GGR: '40.76',
			playerCount: '1',
			payout: '89.35 %',
		},
		{
			identifier: 'pragmaticexternal:BigBassHoldandSpinner',
			id: 4366,
			name: 'Big Bass - Hold & Spinner',
			roundCount: '58',
			totalBet: '17.4',
			totalWin: '8.43',
			GGR: '8.97',
			playerCount: '1',
			payout: '48.45 %',
		},
		{
			identifier: 'slotmill:ChilliBandits',
			id: 5776,
			name: 'Chilli Bandits',
			roundCount: '50',
			totalBet: '40.5',
			totalWin: '25.63',
			GGR: '14.87',
			playerCount: '1',
			payout: '63.28 %',
		},
		{
			identifier: 'playngo:HugoLegacy',
			id: 10837,
			name: 'Hugo Legacy',
			roundCount: '38',
			totalBet: '55',
			totalWin: '23.4',
			GGR: '31.6',
			playerCount: '1',
			payout: '42.55 %',
		},
		{
			identifier: 'pragmaticexternal:HotFiesta1',
			id: 4556,
			name: 'Hot Fiesta',
			roundCount: '39',
			totalBet: '19.5',
			totalWin: '4.98',
			GGR: '14.52',
			playerCount: '1',
			payout: '25.54 %',
		},
		{
			identifier: 'kagaming:DragonInn',
			id: 3078,
			name: 'Dragon Inn',
			roundCount: '36',
			totalBet: '10.8',
			totalWin: '9.35',
			GGR: '1.45',
			playerCount: '1',
			payout: '86.57 %',
		},
		{
			identifier: 'softswiss:BonanzaBillion',
			id: 4135,
			name: 'Bonanza Billion',
			roundCount: '32',
			totalBet: '11',
			totalWin: '6.32',
			GGR: '4.68',
			playerCount: '2',
			payout: '57.45 %',
		},
		{
			identifier: 'everymatrix:BookofSouls',
			id: 2821,
			name: 'Book of Souls',
			roundCount: '35',
			totalBet: '3.5',
			totalWin: '2.5',
			GGR: '1',
			playerCount: '1',
			payout: '71.43 %',
		},
		{
			identifier: 'pragmaticexternal:PubKings',
			id: 10815,
			name: 'Pub Kings',
			roundCount: '30',
			totalBet: '12',
			totalWin: '6',
			GGR: '6',
			playerCount: '1',
			payout: '50 %',
		},
		{
			identifier: 'evolution:BountyRaid2',
			id: 10877,
			name: 'Bounty Raid 2',
			roundCount: '31',
			totalBet: '97',
			totalWin: '33',
			GGR: '64',
			playerCount: '1',
			payout: '34.02 %',
		},
		{
			identifier: 'softswiss:AllLuckyClover5',
			id: 4103,
			name: 'All Lucky Clovers 5',
			roundCount: '35',
			totalBet: '6.9',
			totalWin: '5.3',
			GGR: '1.6',
			playerCount: '1',
			payout: '76.81 %',
		},
		{
			identifier: 'softswiss:ElvisFrogTrueways',
			id: 4186,
			name: 'Elvis Frog TRUEWAYS',
			roundCount: '26',
			totalBet: '11.2',
			totalWin: '1.43',
			GGR: '9.77',
			playerCount: '2',
			payout: '12.77 %',
		},
		{
			identifier: 'netgame:TheBigGameHoldNLink',
			id: 3584,
			name: "The Big Game Hold'N'Link",
			roundCount: '30',
			totalBet: '6',
			totalWin: '1.92',
			GGR: '4.08',
			playerCount: '1',
			payout: '32 %',
		},
		{
			identifier: 'evolution:speed_roulette',
			id: 793,
			name: 'Speed Roulette',
			roundCount: '20',
			totalBet: '101',
			totalWin: '96',
			GGR: '5',
			playerCount: '1',
			payout: '95.05 %',
		},
		{
			identifier: 'pragmaticexternal:BigBassBonanza',
			id: 4364,
			name: 'Big Bass Bonanza',
			roundCount: '23',
			totalBet: '2.3',
			totalWin: '1.4',
			GGR: '0.9',
			playerCount: '1',
			payout: '60.87 %',
		},
		{
			identifier: 'softswiss:AllLuckyClover100',
			id: 4100,
			name: 'All Lucky Clovers 100',
			roundCount: '20',
			totalBet: '13',
			totalWin: '4.3',
			GGR: '8.7',
			playerCount: '1',
			payout: '33.08 %',
		},
		{
			identifier: 'thunderkick:TheFalconHuntress_tk',
			id: 1539,
			name: 'The Falcon Huntress',
			roundCount: '17',
			totalBet: '8.5',
			totalWin: '19.5',
			GGR: '-11',
			playerCount: '1',
			payout: '229.41 %',
		},
		{
			identifier: 'pragmaticexternal:KingdomofTheDead',
			id: 4580,
			name: 'Kingdom of The Dead',
			roundCount: '17',
			totalBet: '1.7',
			totalWin: '0.7',
			GGR: '1',
			playerCount: '1',
			payout: '41.18 %',
		},
		{
			identifier: 'evolution:BigBassAdventure',
			id: 10966,
			name: 'Big Bass Adventure',
			roundCount: '17',
			totalBet: '23.6',
			totalWin: '22.98',
			GGR: '0.62',
			playerCount: '2',
			payout: '97.37 %',
		},
		{
			identifier: 'relax:OutlawsInc92',
			id: 8545,
			name: 'Outlaws Inc',
			roundCount: '14',
			totalBet: '80',
			totalWin: '12.7',
			GGR: '67.3',
			playerCount: '1',
			payout: '15.88 %',
		},
		{
			identifier: 'thunderkick:EsqueletoExplosivo2Reborn92_tk',
			id: 10643,
			name: 'Esqueleto Explosivo 2 Reborn',
			roundCount: '14',
			totalBet: '1.4',
			totalWin: '0.34',
			GGR: '1.06',
			playerCount: '1',
			payout: '24.29 %',
		},
		{
			identifier: 'thunderkick:RidersoftheStorm_tk',
			id: 1532,
			name: 'Riders of the Storm',
			roundCount: '16',
			totalBet: '7.1',
			totalWin: '0.2',
			GGR: '6.9',
			playerCount: '1',
			payout: '2.82 %',
		},
		{
			identifier: 'thunderkick:FlameBusters_tk',
			id: 1503,
			name: 'Flame Busters',
			roundCount: '13',
			totalBet: '6.5',
			totalWin: '1.55',
			GGR: '4.95',
			playerCount: '1',
			payout: '23.85 %',
		},
		{
			identifier: 'thunderkick:Luchadora_tk',
			id: 1519,
			name: 'Luchadora',
			roundCount: '15',
			totalBet: '7.5',
			totalWin: '0.2',
			GGR: '7.3',
			playerCount: '1',
			payout: '2.67 %',
		},
		{
			identifier: 'mascot:blackjack_mg',
			id: 3475,
			name: 'Black Jack',
			roundCount: '11',
			totalBet: '23',
			totalWin: '24',
			GGR: '-1',
			playerCount: '1',
			payout: '104.35 %',
		},
		{
			identifier: 'pragmaticexternal:SugarRush1',
			id: 4742,
			name: 'Sugar Rush',
			roundCount: '10',
			totalBet: '50',
			totalWin: '2.72',
			GGR: '47.28',
			playerCount: '2',
			payout: '5.44 %',
		},
		{
			identifier: 'yggdrasil:SunnyShores',
			id: 1097,
			name: 'Sunny Shores',
			roundCount: '12',
			totalBet: '6',
			totalWin: '7.18',
			GGR: '-1.18',
			playerCount: '1',
			payout: '119.67 %',
		},
		{
			identifier: 'evolution:speed_auto_roulette',
			id: 751,
			name: 'Speed Auto Roulette',
			roundCount: '9',
			totalBet: '39',
			totalWin: '40',
			GGR: '-1',
			playerCount: '1',
			payout: '102.56 %',
		},
		{
			identifier: 'evoplay:EuropeTransit',
			id: 10765,
			name: 'Europe Transit',
			roundCount: '11',
			totalBet: '17.3',
			totalWin: '0',
			GGR: '17.3',
			playerCount: '2',
			payout: '0 %',
		},
		{
			identifier: 'nolimit:FireInTheHolexBomb1',
			id: 7867,
			name: 'Fire In The Hole xBomb',
			roundCount: '7',
			totalBet: '456',
			totalWin: '1,241.2',
			GGR: '-785.2',
			playerCount: '1',
			payout: '272.19 %',
		},
		{
			identifier: 'softswiss:ScrollOfAdventure',
			id: 4292,
			name: 'Scroll of Adventure',
			roundCount: '11',
			totalBet: '2.35',
			totalWin: '0.24',
			GGR: '2.11',
			playerCount: '2',
			payout: '10.21 %',
		},
		{
			identifier: 'thunderkick:Barbershop_Uncut_tk',
			id: 1480,
			name: 'Barbershop: Uncut',
			roundCount: '7',
			totalBet: '3.5',
			totalWin: '0.4',
			GGR: '3.1',
			playerCount: '1',
			payout: '11.43 %',
		},
		{
			identifier: 'yggdrasil:Incinerator',
			id: 1034,
			name: 'Incinerator',
			roundCount: '8',
			totalBet: '1.6',
			totalWin: '0.22',
			GGR: '1.38',
			playerCount: '1',
			payout: '13.75 %',
		},
		{
			identifier: 'evolution:immersive_roulette',
			id: 498,
			name: 'Immersive Roulette',
			roundCount: '8',
			totalBet: '4,000.1',
			totalWin: '0',
			GGR: '4,000.1',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: 'evolution:speed_baccaratf',
			id: 760,
			name: 'Speed Baccarat F',
			roundCount: '5',
			totalBet: '18',
			totalWin: '18',
			GGR: '0',
			playerCount: '1',
			payout: '100 %',
		},
		{
			identifier: 'pragmaticexternal:SweetBonanza',
			id: 4747,
			name: 'Sweet Bonanza',
			roundCount: '5',
			totalBet: '140.4',
			totalWin: '76.68',
			GGR: '63.72',
			playerCount: '2',
			payout: '54.62 %',
		},
		{
			identifier: 'relax:JokerBombs2',
			id: 8382,
			name: 'Joker Bombs',
			roundCount: '5',
			totalBet: '40.6',
			totalWin: '19.18',
			GGR: '21.42',
			playerCount: '1',
			payout: '47.24 %',
		},
		{
			identifier: 'relax:LuckyCloverLady',
			id: 10890,
			name: 'Lucky Clover Lady',
			roundCount: '5',
			totalBet: '10.8',
			totalWin: '0.36',
			GGR: '10.44',
			playerCount: '1',
			payout: '3.33 %',
		},
		{
			identifier: 'relax:ToshiVideoClubrtp',
			id: 8780,
			name: 'Toshi Video Club',
			roundCount: '3',
			totalBet: '48.2',
			totalWin: '32.56',
			GGR: '15.64',
			playerCount: '1',
			payout: '67.55 %',
		},
		{
			identifier: 'yggdrasil:Jokerizer',
			id: 1040,
			name: 'Jokerizer',
			roundCount: '5',
			totalBet: '2.5',
			totalWin: '0',
			GGR: '2.5',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: 'yggdrasil:PumpkinSmash',
			id: 1080,
			name: 'Pumpkin Smash',
			roundCount: '3',
			totalBet: '1.2',
			totalWin: '1.28',
			GGR: '-0.08',
			playerCount: '1',
			payout: '106.67 %',
		},
		{
			identifier: 'evolution:speed_baccaratj',
			id: 764,
			name: 'Speed Baccarat J',
			roundCount: '3',
			totalBet: '14',
			totalWin: '8',
			GGR: '6',
			playerCount: '1',
			payout: '57.14 %',
		},
		{
			identifier: 'evolution:speed_baccarato',
			id: 769,
			name: 'Speed Baccarat O',
			roundCount: '3',
			totalBet: '13',
			totalWin: '8',
			GGR: '5',
			playerCount: '1',
			payout: '61.54 %',
		},
		{
			identifier: 'mascot:wild_phoenix_rises',
			id: 10692,
			name: 'Wild Phoenix Rises',
			roundCount: '2',
			totalBet: '0.5',
			totalWin: '0.18',
			GGR: '0.32',
			playerCount: '1',
			payout: '36 %',
		},
		{
			identifier: 'evolution:speed_baccarati',
			id: 763,
			name: 'Speed Baccarat I',
			roundCount: '2',
			totalBet: '6',
			totalWin: '3.9',
			GGR: '2.1',
			playerCount: '1',
			payout: '65 %',
		},
		{
			identifier: 'softswiss:BookOfPyramids',
			id: 4142,
			name: 'Book of Pyramids',
			roundCount: '3',
			totalBet: '0.27',
			totalWin: '0',
			GGR: '0.27',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: '3oaks:buddha_megaways',
			id: 5813,
			name: 'Buddha Megaways',
			roundCount: '1',
			totalBet: '0.2',
			totalWin: '0',
			GGR: '0.2',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: 'evolution:lightning_roulette',
			id: 546,
			name: 'Lightning Roulette',
			roundCount: '1',
			totalBet: '1.5',
			totalWin: '0',
			GGR: '1.5',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: 'evolution:speed_baccarata',
			id: 755,
			name: 'Speed Baccarat A',
			roundCount: '1',
			totalBet: '6',
			totalWin: '0',
			GGR: '6',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: 'evolution:speed_baccaratc',
			id: 757,
			name: 'Speed Baccarat C',
			roundCount: '1',
			totalBet: '3',
			totalWin: '0',
			GGR: '3',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: 'nolimit:DjPsychoDX1',
			id: 10935,
			name: 'DJ Psycho',
			roundCount: '1',
			totalBet: '1',
			totalWin: '0',
			GGR: '1',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: 'pragmaticexternal:RouletteAzure',
			id: 4678,
			name: 'Roulette 1 - Azure',
			roundCount: '1',
			totalBet: '9.9',
			totalWin: '0',
			GGR: '9.9',
			playerCount: '1',
			payout: '0 %',
		},
	],
	provider: [
		{
			identifier: 'bgaming',
			id: 4,
			name: 'bgaming',
			roundCount: '1,560',
			totalBet: '698.37',
			totalWin: '582.14',
			GGR: '116.23',
			playerCount: '7',
			payout: '83.36 %',
		},
		{
			identifier: 'pragmaticplay',
			id: 58,
			name: 'pragmaticplay',
			roundCount: '1,500',
			totalBet: '2,032.9',
			totalWin: '1,905.64',
			GGR: '127.26',
			playerCount: '11',
			payout: '93.74 %',
		},
		{
			identifier: 'bigtimegaming',
			id: 100,
			name: 'bigtimegaming',
			roundCount: '411',
			totalBet: '227.6',
			totalWin: '191.74',
			GGR: '35.86',
			playerCount: '1',
			payout: '84.24 %',
		},
		{
			identifier: 'spinomenal',
			id: 68,
			name: 'spinomenal',
			roundCount: '396',
			totalBet: '249.55',
			totalWin: '131.85',
			GGR: '117.7',
			playerCount: '4',
			payout: '52.84 %',
		},
		{
			identifier: 'kagaming',
			id: 47,
			name: 'kagaming',
			roundCount: '333',
			totalBet: '153.3',
			totalWin: '137.8',
			GGR: '15.5',
			playerCount: '1',
			payout: '89.89 %',
		},
		{
			identifier: 'evoplay',
			id: 54,
			name: 'evoplay',
			roundCount: '308',
			totalBet: '142',
			totalWin: '85.73',
			GGR: '56.27',
			playerCount: '4',
			payout: '60.37 %',
		},
		{
			identifier: 'hacksaw',
			id: 87,
			name: 'hacksaw',
			roundCount: '144',
			totalBet: '217.6',
			totalWin: '83.64',
			GGR: '133.96',
			playerCount: '3',
			payout: '38.44 %',
		},
		{
			identifier: 'truelab',
			id: 50,
			name: 'truelab',
			roundCount: '137',
			totalBet: '17.73',
			totalWin: '15.05',
			GGR: '2.68',
			playerCount: '1',
			payout: '84.88 %',
		},
		{
			identifier: 'reflexgaming',
			id: 6,
			name: 'reflexgaming',
			roundCount: '90',
			totalBet: '21.8',
			totalWin: '19.42',
			GGR: '2.38',
			playerCount: '1',
			payout: '89.08 %',
		},
		{
			identifier: 'thunderkick',
			id: 24,
			name: 'thunderkick',
			roundCount: '82',
			totalBet: '34.5',
			totalWin: '22.19',
			GGR: '12.31',
			playerCount: '2',
			payout: '64.32 %',
		},
		{
			identifier: 'technology',
			id: 52,
			name: 'technology',
			roundCount: '81',
			totalBet: '8.1',
			totalWin: '6',
			GGR: '2.1',
			playerCount: '1',
			payout: '74.07 %',
		},
		{
			identifier: 'tomhorn',
			id: 67,
			name: 'tomhorn',
			roundCount: '76',
			totalBet: '14.6',
			totalWin: '2.7',
			GGR: '11.9',
			playerCount: '1',
			payout: '18.49 %',
		},
		{
			identifier: 'belatra',
			id: 31,
			name: 'belatra',
			roundCount: '64',
			totalBet: '12.75',
			totalWin: '4.1',
			GGR: '8.65',
			playerCount: '1',
			payout: '32.16 %',
		},
		{
			identifier: 'evolution',
			id: 3,
			name: 'evolution',
			roundCount: '53',
			totalBet: '4,201.6',
			totalWin: '173.9',
			GGR: '4,027.7',
			playerCount: '2',
			payout: '4.14 %',
		},
		{
			identifier: 'slotmill',
			id: 74,
			name: 'slotmill',
			roundCount: '50',
			totalBet: '40.5',
			totalWin: '25.63',
			GGR: '14.87',
			playerCount: '1',
			payout: '63.28 %',
		},
		{
			identifier: 'playngo',
			id: 83,
			name: 'playngo',
			roundCount: '38',
			totalBet: '55',
			totalWin: '23.4',
			GGR: '31.6',
			playerCount: '1',
			payout: '42.55 %',
		},
		{
			identifier: 'spearhead',
			id: 45,
			name: 'spearhead',
			roundCount: '35',
			totalBet: '3.5',
			totalWin: '2.5',
			GGR: '1',
			playerCount: '1',
			payout: '71.43 %',
		},
		{
			identifier: 'redtiger',
			id: 1,
			name: 'redtiger',
			roundCount: '31',
			totalBet: '97',
			totalWin: '33',
			GGR: '64',
			playerCount: '1',
			payout: '34.02 %',
		},
		{
			identifier: 'netgame',
			id: 49,
			name: 'netgame',
			roundCount: '30',
			totalBet: '6',
			totalWin: '1.92',
			GGR: '4.08',
			playerCount: '1',
			payout: '32 %',
		},
		{
			identifier: 'yggdrasil',
			id: 7,
			name: 'yggdrasil',
			roundCount: '28',
			totalBet: '11.3',
			totalWin: '8.68',
			GGR: '2.62',
			playerCount: '2',
			payout: '76.81 %',
		},
		{
			identifier: 'maxwin',
			id: 134,
			name: 'maxwin',
			roundCount: '17',
			totalBet: '23.6',
			totalWin: '22.98',
			GGR: '0.62',
			playerCount: '2',
			payout: '97.37 %',
		},
		{
			identifier: 'mascot',
			id: 48,
			name: 'mascot',
			roundCount: '13',
			totalBet: '23.5',
			totalWin: '24.18',
			GGR: '-0.68',
			playerCount: '2',
			payout: '102.89 %',
		},
		{
			identifier: 'nolimit',
			id: 94,
			name: 'nolimit',
			roundCount: '8',
			totalBet: '457',
			totalWin: '1,241.2',
			GGR: '-784.2',
			playerCount: '2',
			payout: '271.6 %',
		},
		{
			identifier: 'pgsoft',
			id: 98,
			name: 'pgsoft',
			roundCount: '5',
			totalBet: '10.8',
			totalWin: '0.36',
			GGR: '10.44',
			playerCount: '1',
			payout: '3.33 %',
		},
		{
			identifier: 'pragmaticplaylive',
			id: 59,
			name: 'pragmaticplaylive',
			roundCount: '1',
			totalBet: '9.9',
			totalWin: '0',
			GGR: '9.9',
			playerCount: '1',
			payout: '0 %',
		},
		{
			identifier: '3oaks',
			id: 75,
			name: '3oaks',
			roundCount: '1',
			totalBet: '0.2',
			totalWin: '0',
			GGR: '0.2',
			playerCount: '1',
			payout: '0 %',
		},
	],
};

export { gameContant };
export default gameContant;
