export const PERMISSIONS_START = 'PERMISSIONS_START';
export const PERMISSIONS_SUCCESS = 'PERMISSIONS_SUCCESS';
export const PERMISSIONS_ERROR = 'PERMISSIONS_ERROR';
export const SAVE_PERMISSIONS = 'SAVE_PERMISSIONS';
export const SUPER_ADMIN_START = 'SUPER_ADMIN_START';
export const SUPER_ADMIN_SUCCESS = 'SUPER_ADMIN_SUCCESS';
export const SUPER_ADMIN_FAIL = 'SUPER_ADMIN_FAIL;';
export const PERMISSIONS_CLEAR = 'PERMISSIONS_CLEAR';
