export const GET_TICKET_MANAGEMENT_DATA_SUCCESS =
	'GET_TICKET_MANAGEMENT_DATA_SUCCESS';
export const GET_TICKET_MANAGEMENT_DATA_FAIL =
	'GET_TICKET_MANAGEMENT_DATA_FAIL';
export const GET_TICKET_MANAGEMENT_DATA_START =
	'GET_TICKET_MANAGEMENT_DATA_START';

// update ticket status
export const UPDATE_TICKET_STATUS_SUCCESS = 'UPDATE_TICKET_STATUS_SUCCESS';
export const UPDATE_TICKET_STATUS_FAIL = 'UPDATE_TICKET_STATUS_FAIL';
export const UPDATE_TICKET_STATUS_START = 'UPDATE_TICKET_STATUS_START';

// get ticket messages
export const GET_TICKET_MESSAGES_SUCCESS = 'GET_TICKET_MESSAGES_SUCCESS';
export const GET_TICKET_MESSAGES_FAIL = 'GET_TICKET_MESSAGES_FAIL';
export const GET_TICKET_MESSAGES_START = 'GET_TICKET_MESSAGES_START';

// post ticket messages
export const POST_TICKET_MESSAGES_SUCCESS = 'POST_TICKET_MESSAGES_SUCCESS';
export const POST_TICKET_MESSAGES_FAIL = 'POST_TICKET_MESSAGES_FAIL';
export const POST_TICKET_MESSAGES_START = 'POST_TICKET_MESSAGES_START';
