/** Get promotions */
export const GET_PROMOTIONS_START = 'GET_PROMOTIONS_START';
export const GET_PROMOTIONS_SUCCESS = 'GET_PROMOTIONS_SUCCESS';
export const GET_PROMOTIONS_FAIL = 'GET_PROMOTIONS_FAIL';
// Create promotions
export const CREATE_PROMOTIONS_START = 'CREATE_PROMOTIONS_START';
export const CREATE_PROMOTIONS_SUCCESS = 'CREATE_PROMOTIONS_SUCCESS';
export const CREATE_PROMOTIONS_FAIL = 'CREATE_PROMOTIONS_FAIL';
// Update promotions
export const UPDATE_PROMOTIONS_START = 'UPDATE_PROMOTIONS_START';
export const UPDATE_PROMOTIONS_SUCCESS = 'UPDATE_PROMOTIONS_SUCCESS';
export const UPDATE_PROMOTIONS_FAIL = 'UPDATE_PROMOTIONS_FAIL';
export const SELECT_PROMOTION_BY_PAGE = 'SELECT_PROMOTION_BY_PAGE';
// // Delete promotions
export const DELETE_PROMOTIONS_START = 'DELETE_PROMOTIONS_START';
// export const DELETE_PROMOTIONS_SUCCESS = 'DELETE_PROMOTIONS_SUCCESS';
// export const DELETE_PROMOTIONS_FAIL = 'DELETE_PROMOTIONS_FAIL';
