//  GET SUPER ADMIN BANNERS
export const GET_SA_BANNERS = 'GET_SA_BANNERS';
export const GET_SA_BANNERS_SUCCESS = 'GET_SA_BANNERS_SUCCESS';
export const GET_SA_BANNERS_FAIL = 'GET_SA_BANNERS_FAIL';

//  CREATE SUPER ADMIN BANNERS
export const CREATE_SA_BANNERS_START = 'CREATE_SA_BANNERS_START';
export const CREATE_SA_BANNERS_SUCCESS = 'CREATE_SA_BANNERS_SUCCESS';
export const CREATE_SA_BANNERS_FAIL = 'CREATE_SA_BANNERS_FAIL';

//  EDIT SUPER ADMIN BANNERS
export const EDIT_SA_BANNERS_START = 'EDIT_SA_BANNERS_START';
export const EDIT_SA_BANNERS_SUCCESS = 'EDIT_SA_BANNERS_SUCCESS';
export const EDIT_SA_BANNERS_FAIL = 'EDIT_SA_BANNERS_FAIL';

//  GET KYC LABELS
export const GET_DOCUMENT_LABEL = 'GET_DOCUMENT_LABEL';
export const GET_DOCUMENT_LABEL_SUCCESS = 'GET_DOCUMENT_LABEL_SUCCESS';
export const GET_DOCUMENT_LABEL_FAIL = 'GET_DOCUMENT_LABEL_FAIL';

//  CREATE KYC LABELS
export const CREATE_KYC_LABELS_START = 'CREATE_KYC_LABELS_START';
export const CREATE_KYC_LABELS_SUCCESS = 'CREATE_KYC_LABELS_SUCCESS';
export const CREATE_KYC_LABELS_FAIL = 'CREATE_KYC_LABELS_FAIL';

//  EDIT KYC LABELS
export const EDIT_KYC_LABELS_START = 'EDIT_KYC_LABELS_START';
export const EDIT_KYC_LABELS_SUCCESS = 'EDIT_KYC_LABELS_SUCCESS';
export const EDIT_KYC_LABELS_FAIL = 'EDIT_KYC_LABELS_FAIL';

//  GET LOYALTY LEVEL
export const GET_LOYALTY_LEVEL = 'GET_LOYALTY_LEVEL';
export const GET_LOYALTY_LEVEL_SUCCESS = 'GET_LOYALTY_LEVEL_SUCCESS';
export const GET_LOYALTY_LEVEL_FAIL = 'GET_LOYALTY_LEVEL_FAIL';

//  UPDATE LOYALTY LEVEL
export const UPDATE_LOYALTY_LEVEL = 'UPDATE_LOYALTY_LEVEL';
export const UPDATE_LOYALTY_LEVEL_SUCCESS = 'UPDATE_LOYALTY_LEVEL_SUCCESS';
export const UPDATE_LOYALTY_LEVEL_FAIL = 'UPDATE_LOYALTY_LEVEL_FAIL';

// delete SA banners
export const DELETE_SA_BANNERS_START = 'DELETE_SA_BANNERS_START';
export const DELETE_SA_BANNERS_SUCCESS = 'DELETE_SA_BANNERS_SUCCESS';
export const DELETE_SA_BANNERS_FAIL = 'DELETE_SA_BANNERS_FAIL';
