/** Get bonus */
export const GET_BONUS_DETAILS_DATA_SUCCESS = 'GET_BONUS_DETAILS_DATA_SUCCESS';
export const GET_BONUS_DETAILS_DATA_FAIL = 'GET_BONUS_DETAILS_DATA_FAIL';
export const GET_BONUS_DETAILS_DATA = 'GET_BONUS_DETAILS_DATA';

export const UPDATE_SA_BONUS_STATUS_SUCCESS = 'UPDATE_SA_BONUS_STATUS_SUCCESS';
export const UPDATE_SA_BONUS_STATUS_FAIL = 'UPDATE_SA_BONUS_STATUS_FAIL';
export const UPDATE_SA_BONUS_STATUS = 'UPDATE_SA_BONUS_STATUS';

export const GET_BONUS_CURRENCY_CONVERSION_SUCCESS =
  'GET_BONUS_CURRENCY_CONVERSION_SUCCESS';
export const GET_BONUS_CURRENCY_CONVERSION_FAIL =
  'GET_BONUS_CURRENCY_CONVERSION_FAIL';
export const GET_BONUS_CURRENCY_CONVERSION = 'GET_BONUS_CURRENCY_CONVERSION';
export const RESET_BONUS_CURRENCY_CONVERSION =
  'RESET_BONUS_CURRENCY_CONVERSION';

export const GET_BONUS_START = 'GET_BONUS_START';
export const GET_BONUS_SUCCESS = 'GET_BONUS_SUCCESS';
export const GET_BONUS__FAIL = 'GET_BONUS__FAIL';
export const DELETE_BONUS_START = 'DELETE_BONUS_START';
export const DELETE_BONUS_FAIL = 'DELETE_BONUS_FAIL';
export const DELETE_BONUS_COMPLETE = 'DELETE_BONUS_COMPLETE';
