export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

export const GET_USER_DOCUMENTS_SUCCESS = 'GET_USER_DOCUMENTS_SUCCESS';
export const GET_USER_DOCUMENTS_FAIL = 'GET_USER_DOCUMENTS_FAIL';
export const GET_USER_DOCUMENTS = 'GET_USER_DOCUMENTS';

export const GET_USER_BONUS_SUCCESS = 'GET_USER_BONUS_SUCCESS';
export const GET_USER_BONUS_FAIL = 'GET_USER_BONUS_FAIL';
export const GET_USER_BONUS = 'GET_USER_BONUS';

export const GET_USER_COMMENTS_SUCCESS = 'GET_USER_COMMENTS_SUCCESS';
export const GET_USER_COMMENTS_FAIL = 'GET_USER_COMMENTS_FAIL';
export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';

export const CREATE_USER_COMMENT_SUCCESS = 'CREATE_USER_COMMENT_SUCCESS';
export const CREATE_USER_COMMENT_FAIL = 'CREATE_USER_COMMENT_FAIL';
export const CREATE_USER_COMMENT = 'CREATE_USER_COMMENT';

export const RESET_USER_LIMIT_SUCCESS = 'RESET_USER_LIMIT_SUCCESS';
export const RESET_USER_LIMIT_FAIL = 'RESET_USER_LIMIT_FAIL';
export const RESET_USER_LIMIT = 'RESET_USER_LIMIT';
export const RESET_USER_LIMIT_DATA = 'RESET_USER_LIMIT_DATA';

export const DISABLE_USER_SUCCESS = 'DISABLE_USER_SUCCESS';
export const DISABLE_USER_FAIL = 'DISABLE_USER_FAIL';
export const DISABLE_USER = 'DISABLE_USER';

export const UPDATE_SA_USER_STATUS_SUCCESS = 'UPDATE_SA_USER_STATUS_SUCCESS';
export const UPDATE_SA_USER_STATUS_FAIL = 'UPDATE_SA_USER_STATUS_FAIL';
export const UPDATE_SA_USER_STATUS = 'UPDATE_SA_USER_STATUS';

export const MARK_USER_AS_INTERNAL_SUCCESS = 'MARK_USER_AS_INTERNAL_SUCCESS';
export const MARK_USER_AS_INTERNAL_FAIL = 'MARK_USER_AS_INTERNAL_FAIL';
export const MARK_USER_AS_INTERNAL = 'MARK_USER_AS_INTERNAL';

export const VERIFY_USER_EMAIL_SUCCESS = 'VERIFY_USER_EMAIL_SUCCESS';
export const VERIFY_USER_EMAIL_FAIL = 'VERIFY_USER_EMAIL_FAIL';
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL';

export const UPDATE_USER_TAGS_SUCCESS = 'UPDATE_USER_TAGS_SUCCESS';
export const UPDATE_USER_TAGS_FAIL = 'UPDATE_USER_TAGS_FAIL';
export const UPDATE_USER_TAGS = 'UPDATE_USER_TAGS';

export const GET_DUPLICATE_USERS_SUCCESS = 'GET_DUPLICATE_USERS_SUCCESS';
export const GET_DUPLICATE_USERS_FAIL = 'GET_DUPLICATE_USERS_FAIL';
export const GET_DUPLICATE_USERS = 'GET_DUPLICATE_USERS';

export const GET_ALL_BONUS_SUCCESS = 'GET_ALL_BONUS_SUCCESS';
export const GET_ALL_BONUS_FAIL = 'GET_ALL_BONUS_FAIL';
export const GET_ALL_BONUS = 'GET_ALL_BONUS';

export const GET_BONUS_DETAILS_SUCCESS = 'GET_BONUS_DETAILS_SUCCESS';
export const GET_BONUS_DETAILS_FAIL = 'GET_BONUS_DETAILS_FAIL';
export const GET_BONUS_DETAILS = 'GET_BONUS_DETAILS';
export const GET_BONUS_DETAILS_RESET = 'GET_BONUS_DETAILS_RESET';

export const ISSUE_BONUS_SUCCESS = 'ISSUE_BONUS_SUCCESS';
export const ISSUE_BONUS_FAIL = 'ISSUE_BONUS_FAIL';
export const ISSUE_BONUS = 'ISSUE_BONUS';

export const DEPOSIT_TO_OTHER_SUCCESS = 'DEPOSIT_TO_OTHER_SUCCESS';
export const DEPOSIT_TO_OTHER_FAIL = 'DEPOSIT_TO_OTHER_FAIL';
export const DEPOSIT_TO_OTHER = 'DEPOSIT_TO_OTHER';

export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';
export const SEND_PASSWORD_RESET_FAIL = 'SEND_PASSWORD_RESET_FAIL';
export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET';

export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAIL = 'UPDATE_USER_PASSWORD_FAIL';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';

export const MARK_DOCUMENT_REQUIRED_SUCCESS = 'MARK_DOCUMENT_REQUIRED_SUCCESS';
export const MARK_DOCUMENT_REQUIRED_FAIL = 'MARK_DOCUMENT_REQUIRED_FAIL';
export const MARK_DOCUMENT_REQUIRED = 'MARK_DOCUMENT_REQUIRED';
export const MARK_DOCUMENT_REQUIRED_RESET = 'MARK_DOCUMENT_REQUIRED_RESET';

export const CANCEL_USER_BONUS_SUCCESS = 'CANCEL_USER_BONUS_SUCCESS';
export const CANCEL_USER_BONUS_FAIL = 'CANCEL_USER_BONUS_FAIL';
export const CANCEL_USER_BONUS = 'CANCEL_USER_BONUS';

export const RESOLVE_USER_COMMENT_SUCCESS = 'RESOLVE_USER_COMMENT_SUCCESS';
export const RESOLVE_USER_COMMENT_FAIL = 'RESOLVE_USER_COMMENT_FAIL';
export const RESOLVE_USER_COMMENT = 'RESOLVE_USER_COMMENT';

export const ACCEPT_USER_DOC_SUCCESS = 'ACCEPT_USER_DOC_SUCCESS';
export const ACCEPT_USER_DOC_FAIL = 'ACCEPT_USER_DOC_FAIL';
export const ACCEPT_USER_DOC = 'ACCEPT_USER_DOC';

export const UPDATE_KYC_LEVEL_SUCCESS = 'UPDATE_KYC_LEVEL_SUCCESS';
export const UPDATE_KYC_LEVEL__FAIL = 'UPDATE_KYC_LEVEL__FAIL';
export const UPDATE_KYC_LEVEL = 'UPDATE_KYC_LEVEL';

export const GET_REFERRED_USERS_START = 'GET_REFERRED_USERS_START';
export const GET_REFERRED_USERS_SUCCESS = 'GET_REFERRED_USERS_SUCCESS';
export const GET_REFERRED_USERS_FAIL = 'GET_REFERRED_USERS_FAIL';
