export const FETCH_RESTRICTED_COUNTRIES_START =
	'FETCH_RESTRICTED_COUNTRIES_START';
export const FETCH_RESTRICTED_COUNTRIES_FAIL =
	'FETCH_RESTRICTED_COUNTRIES_FAIL';
export const FETCH_RESTRICTED_COUNTRIES_SUCCESS =
	'FETCH_RESTRICTED_COUNTRIES_SUCCESS';

export const FETCH_UNRESTRICTED_COUNTRIES_START =
	'FETCH_UNRESTRICTED_COUNTRIES_START';
export const FETCH_UNRESTRICTED_COUNTRIES_FAIL =
	'FETCH_UNRESTRICTED_COUNTRIES_FAIL';
export const FETCH_UNRESTRICTED_COUNTRIES_SUCCESS =
	'FETCH_UNRESTRICTED_COUNTRIES_SUCCESS';

export const ADD_RESTRICTED_COUNTRIES_START = 'ADD_RESTRICTED_COUNTRIES_START';
export const ADD_RESTRICTED_COUNTRIES_FAIL = 'ADD_RESTRICTED_COUNTRIES_FAIL';
export const ADD_RESTRICTED_COUNTRIES_SUCCESS =
	'ADD_RESTRICTED_COUNTRIES_SUCCESS';
