/** Get registration form fields */
export const GET_REGISTRATION_FIELDS_SUCCESS =
	'GET_REGISTRATION_FIELDS_SUCCESS';
export const GET_REGISTRATION_FIELDS_FAIL = 'GET_REGISTRATION_FIELDS_FAIL';
export const GET_REGISTRATION_FIELDS = 'GET_REGISTRATION_FIELDS';

/** update registration form fields */
export const UPDATE_REGISTRATION_FIELDS_SUCCESS =
	'UPDATE_REGISTRATION_FIELDS_SUCCESS';
export const UPDATE_REGISTRATION_FIELDS_FAIL =
	'UPDATE_REGISTRATION_FIELDS_FAIL';
export const UPDATE_REGISTRATION_FIELDS = 'UPDATE_REGISTRATION_FIELDS';
