/** Get CMS */
export const GET_ALL_CMS_DATA_SUCCESS = 'GET_ALL_CMS_DATA_SUCCESS';
export const GET_ALL_CMS_DATA_FAIL = 'GET_ALL_CMS_DATA_FAIL';
export const GET_ALL_CMS_DATA = 'GET_ALL_CMS_DATA';

/** Get CMS by pageId */
export const GET_CMS_BY_PAGE_ID_SUCCESS = 'GET_CMS_BY_PAGE_ID_SUCCESS';
export const GET_CMS_BY_PAGE_ID_FAIL = 'GET_CMS_BY_PAGE_ID_FAIL';
export const GET_CMS_BY_PAGE_ID = 'GET_CMS_BY_PAGE_ID';

/** CMS Keys */
export const GET_CMS_DYNAMIC_KEYS_SUCCESS = 'GET_CMS_DYNAMIC_KEYS_SUCCESS';
export const GET_CMS_DYNAMIC_KEYS_FAIL = 'GET_CMS_DYNAMIC_KEYS_FAIL';
export const GET_CMS_DYNAMIC_KEYS = 'GET_CMS_DYNAMIC_KEYS';

export const UPDATE_SA_CMS_STATUS_SUCCESS = 'UPDATE_SA_CMS_STATUS_SUCCESS';
export const UPDATE_SA_CMS_STATUS_FAIL = 'UPDATE_SA_CMS_STATUS_FAIL';
export const UPDATE_SA_CMS_STATUS = 'UPDATE_SA_CMS_STATUS';

export const CREATE_SA_CMS_SUCCESS = 'CREATE_SA_CMS_SUCCESS';
export const CREATE_SA_CMS_FAIL = 'CREATE_SA_CMS_FAIL';
export const CREATE_SA_CMS = 'CREATE_SA_CMS';

export const UPDATE_SA_CMS_SUCCESS = 'UPDATE_SA_CMS_SUCCESS';
export const UPDATE_SA_CMS_FAIL = 'UPDATE_SA_CMS_FAIL';
export const UPDATE_SA_CMS = 'UPDATE_SA_CMS';
