/** Get Email Templates */
export const GET_ALL_EMAIL_TEMPLATES_SUCCESS = 'GET_EMAIL_TEMPLATES_SUCCESS';
export const GET_ALL_EMAIL_TEMPLATES_FAIL = 'GET_EMAIL_TEMPLATES_FAIL';
export const GET_ALL_EMAIL_TEMPLATES = 'GET_EMAIL_TEMPLATES';

/** Get Email Template */
export const GET_EMAIL_TEMPLATE_SUCCESS = 'GET_EMAIL_TEMPLATE_SUCCESS';
export const GET_EMAIL_TEMPLATE_FAIL = 'GET_EMAIL_TEMPLATE_FAIL';
export const GET_EMAIL_TEMPLATE = 'GET_EMAIL_TEMPLATE';

/** Get Dynamic Keys */
export const GET_DYNAMIC_KEYS_SUCCESS = 'GET_DYNAMIC_KEYS_SUCCESS';
export const GET_DYNAMIC_KEYS_FAIL = 'GET_DYNAMIC_KEYS_FAIL';
export const GET_DYNAMIC_KEYS = 'GET_DYNAMIC_KEYS';

/** Get Email Types */
export const GET_EMAIL_TYPES_SUCCESS = 'GET_EMAIL_TYPES_SUCCESS';
export const GET_EMAIL_TYPES_FAIL = 'GET_EMAIL_TYPES_FAIL';
export const GET_EMAIL_TYPES = 'GET_EMAIL_TYPES';

/** Get Image gallery */
export const GET_IMAGE_GALLERY_SUCCESS = 'GET_IMAGE_GALLERY_SUCCESS';
export const GET_IMAGE_GALLERY_FAIL = 'GET_IMAGE_GALLERY_FAIL';
export const GET_IMAGE_GALLERY = 'GET_IMAGE_GALLERY';

/** Get upload gallery */
export const UPLOAD_IMAGE_GALLERY_SUCCESS = 'UPLOAD_IMAGE_GALLERY_SUCCESS';
export const UPLOAD_IMAGE_GALLERY_FAIL = 'UPLOAD_IMAGE_GALLERY_FAIL';
export const UPLOAD_IMAGE_GALLERY = 'UPLOAD_IMAGE_GALLERY';

/** Get delete gallery */
export const DELETE_IMAGE_GALLERY_SUCCESS = 'DELETE_IMAGE_GALLERY_SUCCESS';
export const DELETE_IMAGE_GALLERY_FAIL = 'DELETE_IMAGE_GALLERY_FAIL';
export const DELETE_IMAGE_GALLERY = 'DELETE_IMAGE_GALLERY';

/** Reset Email Templates */
export const RESET_EMAIL_TEMPLATES = 'RESET_EMAIL_TEMPLATES';

/** test email template */
export const TEST_EMAIL_TEMPLATE_SUCCESS = 'TEST_EMAIL_TEMPLATE_SUCCESS';
export const TEST_EMAIL_TEMPLATE_FAIL = 'TEST_EMAIL_TEMPLATE_FAIL';
export const TEST_EMAIL_TEMPLATE = 'TEST_EMAIL_TEMPLATE';

/** Create Email Templates */
export const CREATE_EMAIL_TEMPLATE_SUCCESS = 'CREATE_EMAIL_TEMPLATE_SUCCESS';
export const CREATE_EMAIL_TEMPLATE_FAIL = 'CREATE_EMAIL_TEMPLATE_FAIL';
export const CREATE_EMAIL_TEMPLATE = 'CREATE_EMAIL_TEMPLATE';

/** Update Email Templates */
export const UPDATE_EMAIL_TEMPLATE_SUCCESS = 'UPDATE_EMAIL_TEMPLATE_SUCCESS';
export const UPDATE_EMAIL_TEMPLATE_FAIL = 'UPDATE_EMAIL_TEMPLATE_FAIL';
export const UPDATE_EMAIL_TEMPLATE = 'UPDATE_EMAIL_TEMPLATE';

/** delete Email Templates */
export const DELETE_EMAIL_TEMPLATE_SUCCESS = 'DELETE_EMAIL_TEMPLATE_SUCCESS';
export const DELETE_EMAIL_TEMPLATE_FAIL = 'DELETE_EMAIL_TEMPLATE_FAIL';
export const DELETE_EMAIL_TEMPLATE = 'DELETE_EMAIL_TEMPLATE';

/** Send bulk user Emails */
export const SEND_PLAYERS_EMAIL_START = 'SEND_PLAYERS_EMAIL_START';
export const SEND_PLAYERS_EMAIL_SUCCESS = 'SEND_PLAYERS_EMAIL_SUCCESS';
export const SEND_PLAYERS_EMAIL_FAIL = 'SEND_PLAYERS_EMAIL_FAIL';
