// Get Game_Report_List view
export const GET_GAME_REPORT_LIST_START = 'GET_GAME_REPORT_LIST_START';
export const GET_GAME_REPORT_LIST_SUCCESS = 'GET_GAME_REPORT_LIST_SUCCESS';
export const GET_GAME_REPORT_LIST_FAIL = 'GET_GAME_REPORT_LIST_FAIL';
