/** Notice Keys */

export const CREATE_BONUS_DROP_SUCCESS = 'CREATE_BONUS_DROP_SUCCESS';
export const CREATE_BONUS_DROP_FAIL = 'CREATE_BONUS_DROP_FAIL';
export const CREATE_BONUS_DROP = 'CREATE_BONUS_DROP';

export const GET_ALL_BONUS_DROP_SUCCESS = 'GET_ALL_BONUS_DROP_SUCCESS';
export const GET_ALL_BONUS_DROP_FAIL = 'GET_ALL_BONUS_DROP_FAIL';
export const GET_ALL_BONUS_DROP = 'GET_ALL_BONUS_DROP';

