export const GET_CHATRAIN_DATA_SUCCESS = 'GET_CHATRAIN_DATA_SUCCESS';
export const GET_CHATRAIN_DATA_FAIL = 'GET_CHATRAIN_DATA_FAIL';
export const GET_CHATRAIN_DATA = 'GET_CHATRAIN_DATA';

export const CREATE_CHATRAIN_SUCCESS = 'CREATE_CHATRAIN_SUCCESS';
export const CREATE_CHATRAIN_FAIL = 'CREATE_CHATRAIN_FAIL';
export const CREATE_CHATRAIN = 'CREATE_CHATRAIN';

export const UPDATE_CHATRAIN_SUCCESS = 'UPDATE_CHATRAIN_SUCCESS';
export const UPDATE_CHATRAIN_FAIL = 'UPDATE_CHATRAIN_FAIL';
export const UPDATE_CHATRAIN = 'UPDATE_CHATRAIN';

export const DELETE_CHATRAIN_SUCCESS = 'DELETE_CHATRAIN_SUCCESS';
export const DELETE_CHATRAIN_FAIL = 'DELETE_CHATRAIN_FAIL';
export const DELETE_CHATRAIN = 'DELETE_CHATRAIN';

export const RESET_CHATRAIN = 'RESET_CHATRAIN';
