// get Providers
export const FETCH_SPIN_WHEEL_LIST_START = 'FETCH_SPIN_WHEEL_LIST_START';
export const FETCH_SPIN_WHEEL_LIST_FAIL = 'FETCH_SPIN_WHEEL_LIST_FAIL';
export const FETCH_SPIN_WHEEL_LIST_SUCCESS = 'FETCH_SPIN_WHEEL_LIST_SUCCESS';

// edit providers
export const EDIT_SPIN_WHEEL_LIST_SUCCESS = 'EDIT_SPIN_WHEEL_LIST_SUCCESS';
export const EDIT_SPIN_WHEEL_LIST_FAIL = 'EDIT_SPIN_WHEEL_LIST_FAIL';
export const EDIT_SPIN_WHEEL_LIST_START = 'EDIT_SPIN_WHEEL_LIST_START';
