export const FETCH_CASINO_TRANSACTIONS_START =
	'FETCH_CASINO_TRANSACTIONS_START';
export const FETCH_CASINO_TRANSACTIONS_FAIL = 'FETCH_CASINO_TRANSACTIONS_FAIL';
export const FETCH_CASINO_TRANSACTIONS_SUCCESS =
	'FETCH_CASINO_TRANSACTIONS_SUCCESS';
