// get Providers
export const GET_CASINO_PROVIDERS_DATA_SUCCESS =
	'GET_CASINO_PROVIDERS_DATA_SUCCESS';
export const GET_CASINO_PROVIDERS_DATA_FAIL = 'GET_CASINO_PROVIDERS_DATA_FAIL';
export const GET_CASINO_PROVIDERS_DATA = 'GET_CASINO_PROVIDERS_DATA';

// create providers
export const CREATE_CASINO_PROVIDERS_SUCCESS =
	'CREATE_CASINO_PROVIDERS_SUCCESS';
export const CREATE_CASINO_PROVIDERS_FAIL = 'CREATE_CASINO_PROVIDERS_FAIL';
export const CREATE_CASINO_PROVIDERS = 'CREATE_CASINO_PROVIDERS';

// edit providers
export const EDIT_CASINO_PROVIDERS_SUCCESS = 'EDIT_CASINO_PROVIDERS_SUCCESS';
export const EDIT_CASINO_PROVIDERS_FAIL = 'EDIT_CASINO_PROVIDERS_FAIL';
export const EDIT_CASINO_PROVIDERS = 'EDIT_CASINO_PROVIDERS';

/** Get CASINO_CATEGORY */
export const GET_CASINO_CATEGORY_DATA_SUCCESS =
	'GET_CASINO_CATEGORY_DATA_SUCCESS';
export const GET_CASINO_CATEGORY_DATA_FAIL = 'GET_CASINO_CATEGORY_DATA_FAIL';
export const GET_CASINO_CATEGORY_DATA = 'GET_CASINO_CATEGORY_DATA';

/** Create CASINO_CATEGORY */
export const CREATE_CASINO_CATEGORY_SUCCESS = 'CREATE_CASINO_CATEGORY_SUCCESS';
export const CREATE_CASINO_CATEGORY_FAIL = 'CREATE_CASINO_CATEGORY_FAIL';
export const CREATE_CASINO_CATEGORY_START = 'CREATE_CASINO_CATEGORY_START';

// edit category
export const EDIT_CASINO_CATEGORY_SUCCESS = 'EDIT_CASINO_CATEGORY_SUCCESS';
export const EDIT_CASINO_CATEGORY_FAIL = 'EDIT_CASINO_CATEGORY_FAIL';
export const EDIT_CASINO_CATEGORY = 'EDIT_CASINO_CATEGORY';

// get CASINO_SUB_CATEGORY
export const GET_CASINO_SUB_CATEGORY_DATA_SUCCESS =
	'GET_CASINO_SUB_CATEGORY_DATA_SUCCESS';
export const GET_CASINO_SUB_CATEGORY_DATA_FAIL =
	'GET_CASINO_SUB_CATEGORY_DATA_FAIL';
export const GET_CASINO_SUB_CATEGORY_DATA = 'GET_CASINO_SUB_CATEGORY_DATA';

/** Create CASINO_SUBCATEGORY */
export const CREATE_CASINO_SUBCATEGORY_SUCCESS =
	'CREATE_CASINO_SUBCATEGORY_SUCCESS';
export const CREATE_CASINO_SUBCATEGORY_FAIL = 'CREATE_CASINO_SUBCATEGORY_FAIL';
export const CREATE_CASINO_SUBCATEGORY_START =
	'CREATE_CASINO_SUBCATEGORY_START';

/** Edit CASINO_SUBCATEGORY */
export const EDIT_CASINO_SUBCATEGORY_SUCCESS =
	'EDIT_CASINO_SUBCATEGORY_SUCCESS';
export const EDIT_CASINO_SUBCATEGORY_FAIL = 'EDIT_CASINO_SUBCATEGORY_FAIL';
export const EDIT_CASINO_SUBCATEGORY_START = 'EDIT_CASINO_SUBCATEGORY_START';

/** Get CASINO_GAMES */
export const GET_CASINO_GAMES_SUCCESS = 'GET_CASINO_GAMES_SUCCESS';
export const GET_CASINO_GAMES_FAIL = 'GET_CASINO_GAMES_FAIL';
export const GET_CASINO_GAMES = 'GET_CASINO_GAMES';

/** Edit CASINO_GAMES */
export const EDIT_CASINO_GAMES_SUCCESS = 'EDIT_CASINO_GAMES_SUCCESS';
export const EDIT_CASINO_GAMES_FAIL = 'EDIT_CASINO_GAMES_FAIL';
export const EDIT_CASINO_GAMES_START = 'EDIT_CASINO_GAMES_START';

// get Languages
export const GET_LANGUAGE_DATA_SUCCESS = 'GET_LANGUAGE_DATA_SUCCESS';
export const GET_LANGUAGE_DATA_FAIL = 'GET_LANGUAGE_DATA_FAIL';
export const GET_LANGUAGE_DATA_START = 'GET_LANGUAGE_DATA_START';

// update casino status
export const UPDATE_CASINO_STATUS_SUCCESS = 'UPDATE_CASINO_STATUS_SUCCESS';
export const UPDATE_CASINO_STATUS_FAIL = 'UPDATE_CASINO_STATUS_FAIL';
export const UPDATE_CASINO_STATUS_START = 'UPDATE_CASINO_STATUS_START';

// update casino games category status
export const UPDATE_SA_CASINO_GAMES_STATUS_SUCCESS =
	'UPDATE_SA_CASINO_GAMES_STATUS_SUCCESS';
export const UPDATE_SA_CASINO_GAMES_STATUS_FAIL =
	'UPDATE_SA_CASINO_GAMES_STATUS_FAIL';
export const UPDATE_SA_CASINO_GAMES_STATUS_START =
	'UPDATE_SA_CASINO_GAMES_STATUS_START';

// update casino games IS FEATURED status
export const UPDATE_GAME_ISFEATURED_START = 'UPDATE_GAME_ISFEATURED_START';
export const UPDATE_GAME_ISFEATURED_SUCCESS = 'UPDATE_GAME_ISFEATURED_SUCCESS';
export const UPDATE_GAME_ISFEATURED_FAIL = 'UPDATE_GAME_ISFEATURED_FAIL';

// add game to casino subcategory
export const ADD_GAME_TO_CASINO_SUB_CATEGORY_START =
	'ADD_GAME_TO_CASINO_SUB_CATEGORY_START';
export const ADD_GAME_TO_CASINO_SUB_CATEGORY_SUCCESS =
	'ADD_GAME_TO_CASINO_SUB_CATEGORY_SUCCESS';
export const ADD_GAME_TO_CASINO_SUB_CATEGORY_FAIL =
	'ADD_GAME_TO_CASINO_SUB_CATEGORY_FAIL';

// delete casino subcategory
export const DELETE_CASINO_SUB_CATEGORY_START =
	'DELETE_CASINO_SUB_CATEGORY_START';
export const DELETE_CASINO_SUB_CATEGORY_SUCCESS =
	'DELETE_CASINO_SUB_CATEGORY_SUCCESS';
export const DELETE_CASINO_SUB_CATEGORY_FAIL =
	'DELETE_CASINO_SUB_CATEGORY_FAIL';

// delete casino games
export const DELETE_CASINO_GAMES_START = 'DELETE_CASINO_GAMES_START';
export const DELETE_CASINO_GAMES_SUCCESS = 'DELETE_CASINO_GAMES_SUCCESS';
export const DELETE_CASINO_GAMES_FAIL = 'DELETE_CASINO_GAMES_FAIL';

// reorder casino category
export const REORDER_CASINO_CATEGORY_START = 'REORDER_CASINO_CATEGORY_START';
export const REORDER_CASINO_CATEGORY_SUCCESS =
	'REORDER_CASINO_CATEGORY_SUCCESS';
export const REORDER_CASINO_CATEGORY_FAIL = 'REORDER_CASINO_CATEGORY_FAIL';

// reorder casino sub category
export const REORDER_CASINO_SUB_CATEGORY_START =
	'REORDER_CASINO_SUB_CATEGORY_START';
export const REORDER_CASINO_SUB_CATEGORY_SUCCESS =
	'REORDER_CASINO_SUB_CATEGORY_SUCCESS';
export const REORDER_CASINO_SUB_CATEGORY_FAIL =
	'REORDER_CASINO_SUB_CATEGORY_FAIL';

// reorder casino games
export const REORDER_CASINO_GAMES_START = 'REORDER_CASINO_GAMES_START';
export const REORDER_CASINO_GAMES_SUCCESS = 'REORDER_CASINO_GAMES_SUCCESS';
export const REORDER_CASINO_GAMES_FAIL = 'REORDER_CASINO_GAMES_FAIL';

// reset casino games state
export const RESET_CASINO_STATE = 'RESET_CASINO_STATE';
