export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const UPDATE_SITE_CONFIGURATION_START =
	'UPDATE_SITE_CONFIGURATION_START';
export const UPDATE_SITE_CONFIGURATION_FAIL = 'UPDATE_SITE_CONFIGURATION_FAIL';
export const UPDATE_SITE_CONFIGURATION_SUCCESS =
	'UPDATE_SITE_CONFIGURATION_SUCCESS';

export const RESET_PROFILE_PASSWORD_START = 'RESET_PROFILE_PASSWORD_START';
export const RESET_PROFILE_PASSWORD_FAIL = 'RESET_PROFILE_PASSWORD_FAIL';
export const RESET_PROFILE_PASSWORD_SUCCESS = 'RESET_PROFILE_PASSWORD_SUCCESS';
