export const FETCH_REVIEW_MANAGEMENT_START = 'FETCH_REVIEW_MANAGEMENT_START';
export const FETCH_REVIEW_MANAGEMENT_FAIL = 'FETCH_REVIEW_MANAGEMENT_FAIL';
export const FETCH_REVIEW_MANAGEMENT_SUCCESS =
	'FETCH_REVIEW_MANAGEMENT_SUCCESS';
export const CREATE_REVIEW_START = 'CREATE_REVIEW_START';
export const CREATE_REVIEW_FAIL = 'CREATE_REVIEW_FAIL';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
