export const GET_ALL_SOCIAL_LINKS = 'GET_ALL_SOCIAL_LINKS';
export const GET_ALL_SOCIAL_LINKS_SUCCESS = 'GET_ALL_SOCIAL_LINKS_SUCCESS';
export const GET_ALL_SOCIAL_LINKS_FAIL = 'GET_ALL_SOCIAL_LINKS_FAIL';

export const CREATE_SOCIAL_LINK = 'CREATE_SOCIAL_LINK';
export const CREATE_SOCIAL_LINK_SUCCESS = 'CREATE_SOCIAL_LINK_SUCCESS';
export const CREATE_SOCIAL_LINK_FAIL = 'CREATE_SOCIAL_LINK_FAIL';

export const UPDATE_SOCIAL_LINK = 'UPDATE_SOCIAL_LINK';
export const UPDATE_SOCIAL_LINK_SUCCESS = 'UPDATE_SOCIAL_LINK_SUCCESS';
export const UPDATE_SOCIAL_LINK_FAIL = 'UPDATE_SOCIAL_LINK_FAIL';

export const DELETE_SOCIAL_LINK = 'DELETE_SOCIAL_LINK';
export const DELETE_SOCIAL_LINK_SUCCESS = 'DELETE_SOCIAL_LINK_SUCCESS';
export const DELETE_SOCIAL_LINK_FAIL = 'DELETE_SOCIAL_LINK_FAIL';

// export const TOGGLE_SOCIAL_LINK_STATUS = 'TOGGLE_SOCIAL_LINK_STATUS';
// export const TOGGLE_SOCIAL_LINK_STATUS_SUCCESS = 'TOGGLE_SOCIAL_LINK_STATUS_SUCCESS';
// export const TOGGLE_SOCIAL_LINK_STATUS_FAIL = 'TOGGLE_SOCIAL_LINK_STATUS_FAIL';
