export const FETCH_WITHDRAW_REQUESTS_START = 'FETCH_WITHDRAW_REQUESTS_START';
export const FETCH_WITHDRAW_REQUESTS_FAIL = 'FETCH_WITHDRAW_REQUESTS_FAIL';
export const FETCH_WITHDRAW_REQUESTS_SUCCESS =
	'FETCH_WITHDRAW_REQUESTS_SUCCESS';

export const UPDATE_WITHDRAW_REQUEST_START = 'UPDATE_WITHDRAW_REQUEST_START';
export const UPDATE_WITHDRAW_REQUEST_FAIL = 'UPDATE_WITHDRAW_REQUEST_FAIL';
export const UPDATE_WITHDRAW_REQUEST_SUCCESS =
	'UPDATE_WITHDRAW_REQUEST_SUCCESS';
