/** Get Bet settings */
export const GET_BET_SETTINGS_DATA_SUCCESS = 'GET_BET_SETTINGS_DATA_SUCCESS';
export const GET_BET_SETTINGS_DATA_FAIL = 'GET_BET_SETTINGS_DATA_FAIL';
export const GET_BET_SETTINGS_DATA = 'GET_BET_SETTINGS_DATA';

// Create Bet Settings
export const CREATE_BET_SETTINGS_SUCCESS = 'CREATE_BET_SETTINGS_SUCCESS';
export const CREATE_BET_SETTINGS_FAIL = 'CREATE_BET_SETTINGS_FAIL';
export const CREATE_BET_SETTINGS_START = 'CREATE_BET_SETTINGS_START';

// Edit Bet Settings
export const EDIT_BET_SETTINGS_SUCCESS = 'EDIT_BET_SETTINGS_SUCCESS';
export const EDIT_BET_SETTINGS_FAIL = 'EDIT_BET_SETTINGS_FAIL';
export const EDIT_BET_SETTINGS_START = 'EDIT_BET_SETTINGS_START';
